import img1 from "../../public/assets/img/photo1.jpg";
import img2 from "../../public/assets/img/photo2.jpg";
import img3 from "../../public/assets/img/photo3.jpg";
import img4 from "../../public/assets/img/photo4.jpg";
import img5 from "../../public/assets/img/photo5.jpg";
import img6 from "../../public/assets/img/photo6.jpg";
import img7 from "../../public/assets/img/photo7.png";
import img8 from "../../public/assets/img/photo8.png";
import img9 from "../../public/assets/img/photo9.png";
import img10 from "../../public/assets/img/photo10.png";
import img11 from "../../public/assets/img/photo11.png";
import img12 from "../../public/assets/img/photo12.png";
import img13 from "../../public/assets/img/photo13.png";
import img14 from "../../public/assets/img/photo2.jpg";

const tovar = [
  {
    id: 1,
    image: img2,
    alt: "labartory tools",
    title: "Дерматологическое оборудование",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "260 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 2,
    image: img1,
    alt: "labartory tools",
    title: "Оборудование для анастезиологии",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "310 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 3,
    image: img6,

    alt: "labartory tools",
    title: "Ветеринарное оборудование",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "400 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 4,
    image: img3,

    alt: "labartory tools",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "260 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    image: img6,
    alt: "Товар 1",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "290 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    image: img13,
    alt: "Товар 2",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "310 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 7,
    image: img7,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "500 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    id: 8,
    image: img5,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "399 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 9,
    image: img9,
    alt: "labartory tools",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "490 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    id: 10,
    image: img10,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "260 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 11,
    image: img11,
    alt: "labartory tools",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "300 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    id: 12,
    image: img12,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "277 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 13,
    image: img13,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "400 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 14,
    image: img14,
    alt: "labartory tools",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "350 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 1,
    image: img2,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "260 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 2,
    image: img1,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "310 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 3,
    image: img6,

    alt: "labartory tools",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "400 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 4,
    image: img6,

    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "260 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    image: img7,
    alt: "Товар 1",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "290 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    image: img8,
    alt: "Товар 2",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "310 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 7,
    image: img7,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "500 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    id: 8,
    image: img5,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "399 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 9,
    image: img9,
    alt: "labartory tools",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "490 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    id: 10,
    image: img10,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "260 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 11,
    image: img11,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "300 000 руб.",
    label: "Новинка",
    labelClass: "bg-[#088269]",
  },
  {
    id: 12,
    image: img12,
    alt: "labartory tools",
    title: "Мебель для медецинских целей",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "277 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
  {
    id: 13,
    image: img13,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "400 000 руб.",
    label: "Хит продаж",
    labelClass: "bg-[#59599A]",
  },
  {
    id: 14,
    image: img14,
    alt: "labartory tools",
    title: "Анализатор мочи MIND UA-66",
    desc: "Артикул: 213134",
    position: "В наличии",
    price: "350 000 руб.",
    label: "-30%",
    labelClass: "bg-yellow-500",
  },
];
export default tovar;